nginx
location *\.(js|css|pngljpgljpeg|gif|ico|svg)${
expires 1y;
M
add_headerCache-Control"public,immutable";
location/{
proxy_cache ghost_cache;
proxy_cache_valid 200 1h;
proxy_cache_use_stale error timeoutupdating http_500;
proxy_pass http://127.0.0.1:2368;
